### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by davidmoshal** [Vovaman/start_ESP32_with_micropython#9]
really enjoyed the detail in this repo, including discussions of:  
- pyenv
- pipenv
- vscode plugin
- flashing
etc.

coming at micropython from Typescript and Kotlin background, all of the above has been a somewhat frustrating experience with other projects.

Thank you!

**Comment by davidmoshal** [comment]
Some feedback, in a similar vein, the port clearly can't be hard-coded, on macos this will help find the port:

```sh
ls /dev | grep tty
```

**Comment by Vovaman** [comment]
I'm glad to be useful. 
...and `ls /dev | grep tty` returns many ports, so, plug-in and -out guarantees the result )
